#
# Create required Kubernetes stuff.
#
# Original file provided by Torchbox Ltd.

apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kube-system
  name: dynamic-hostpath-provisioner

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: dynamic-hostpath-provisioner
subjects:
- kind: ServiceAccount
  name: dynamic-hostpath-provisioner
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:persistent-volume-provisioner

---

# The default system:persistent-volume-provisioner role in Kubernetes 1.8 is
# insufficient:
#
# I1007 18:09:10.073558       1 controller.go:874] cannot start watcher for PVC default/testpvc: events is forbidden: User "system:serviceaccount:kube-system:dynamic-hostpath-provisioner" cannot list events in the namespace "default": access denied

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dynamic-hostpath-provisioner-extra
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
  - list
  - get
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dynamic-hostpath-provisioner-extra
subjects:
- kind: ServiceAccount
  namespace: kube-system
  name: dynamic-hostpath-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dynamic-hostpath-provisioner-extra

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dynamic-hostpath-provisioner
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamic-hostpath-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dynamic-hostpath-provisioner

    spec:
      serviceAccountName: dynamic-hostpath-provisioner

      volumes:
      - name: volumes
        hostPath:
          path: /dynamic_dirs

      containers:
      - name: dynamic-hostpath-provisioner
        image: kazhar/k8s-dynamic-hostpath-provisioner:develop

        volumeMounts:
        - name: volumes
          mountPath: /dynamic_dirs

        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi
